# This is a comment

# application is mandatory
application: timebot-simple

# version is mandatory
version: 3-13

# runtime is mandatory
runtime: go

# api_version is mandatory
api_version: go1

# handlers is mandatory
handlers:
- url: /.*
  script: _go_app
